add per engine osruntime control to remotehost endpoint

diff --git a/endpoints/remotehost/remotehost b/endpoints/remotehost/remotehost
--- a/endpoints/remotehost/remotehost
+++ b/endpoints/remotehost/remotehost
@@ -43,12 +43,13 @@ fi
 chroot_rbind_mounts="proc dev sys lib/modules usr/src boot var/run"
 
 endpoint_name="remotehost"
-osruntime="chroot"
 image_cache_size=3
 userenv="rhubi8"
 user="root"
 declare -A cpuPartitioning
 declare -A numaNode
+declare -A osruntime
+osruntime[default]="chroot"
 host_mounts=""
 
 function endpoint_remotehost_test_stop() {
@@ -127,7 +128,7 @@ function endpoint_remotehost_test_start() {
 }
 
 function cleanup_osruntime() {
-    local container_name container_image
+    local container_name container_image this_cs_label tmp_osruntime data_file
     echo "Doing osruntime cleanup"
     echo
     echo "All mounts on this remote host:"
@@ -139,35 +140,46 @@ function cleanup_osruntime() {
     echo "All podman container mounts:"
     do_ssh $user@$host podman mount
     echo
-    container_name="${endpoint_label}_${run_id}"
-    if [ "$osruntime" == "chroot" ]; then
 
-        if [ -e $endpoint_run_dir/chroot-container-mount.txt ]; then
-            for container_mount in `cat $endpoint_run_dir/chroot-container-mount.txt`; do
-                for fs in ${chroot_rbind_mounts}; do
-                    echo "Removing ${fs} from ${container_mount}"
-                    do_ssh $user@$host umount --verbose --recursive ${container_mount}/${fs}
-                    echo
-                done
-            done
-        else
-            echo "WARNING: the file with container base mount [$endpoint_run_dir/chroot-container-mount.txt] could not be found"
+    for this_cs_label in ${clients[@]} ${servers[@]}; do
+        tmp_osruntime=${osruntime[default]}
+        set +u
+        if [ ! -z "${osruntime[$this_cs_label]}" ]; then
+            tmp_osruntime=${osruntime[$this_cs_label]}
         fi
+        set -u
 
-        if [ -e $endpoint_run_dir/chroot-container-id.txt ]; then
-            for container_id in `cat $endpoint_run_dir/chroot-container-id.txt`; do
-                echo "Removing container with id [$container_id]"
-                do_ssh $user@$host podman rm $container_id
-            done
-        else
-            echo "WARNING: the file with container base mount [$endpoint_run_dir/chroot-container-id.txt] could not be found"
-        fi
-    elif [ "${osruntime}" == "podman" ]; then
-        for this_cs_label in ${clients[@]} ${servers[@]}; do
-            container_name="${endpoint_label}_${run_id}_${this_cs_label}"
+        if [ "${tmp_osruntime}" == "chroot" ]; then
+            data_file=${endpoint_run_dir}/chroot-container-mount.txt
+            if [ -e ${data_file} ]; then
+                while read tmp_cs_label container_mount; do
+                    if [ "${this_cs_label}" == "${tmp_cs_label}" ]; then
+                        for fs in ${chroot_rbind_mounts}; do
+                            echo "Removing ${fs} from ${container_mount}"
+                            do_ssh ${user}@${host} umount --verbose --recursive ${container_mount}/${fs}
+                        done
+                    fi
+                done < ${data_file}
+            else
+                echo "WARNING: the file with container base mount [${data_file}] could not be found"
+            fi
+
+            data_file=$endpoint_run_dir/chroot-container-id.txt
+            if [ -e ${data_file} ]; then
+                while read tmp_cs_label container_id; do
+                    if [ "${this_cs_label}" == "${tmp_cs_label}" ]; then
+                        echo "Removing container with id [${container_id}]"
+                        do_ssh ${user}@${host} podman rm ${container_id}
+                    fi
+                done < ${data_file}
+            else
+                echo "WARNING: the file with container base mount [${data_file}] could not be found"
+            fi
+        elif [ "${tmp_osruntime}" == "podman" ]; then
+            container_name="${endpoint_label}_${run_id}_${this_cs_label}_${tmp_osruntime}"
             do_ssh $user@$host podman rm ${container_name}
-        done
-    fi
+        fi
+    done
 
     # manage container image cache on the host
     echo "Performing container image cache management:"
@@ -199,14 +211,32 @@ function process_remotehost_opts() {
                 addto_clients_servers "$arg" "$val"
                 ;;
             osruntime)
-                case "$val" in
-                    chroot|podman)
-                        osruntime=$val
-                        ;;
-                    *)
-                        exit_error "osruntime $val not supported"
-                        ;;
-                esac
+                # osruntime is per engine:
+                # option format:: osruntime:<engine-name>:<value>
+                # <engine-name> can be 'default' to any engine that is not explicitly specified
+                # for backwards compability values in the form of 'osruntime:<value>' will map to 'osruntime:default:<value>'
+                #TODO: validate correct format of <client-server-label>
+
+                # backwards compability transformation
+                if ! echo "${val}" | grep -q -e '[a-zA-Z0-9\-]:[a-zA-Z0-9\-]'; then
+                    val="default:${val}"
+                fi
+
+                name=$(echo "${val}" | awk -F: '{ print $1 }')
+                value=$(echo "${val}" | awk -F: '{ print $2 }')
+
+                if [ -z "${name}" -o -z "${value}" ]; then
+                    exit_error "Could not properly decode osruntime for '${val}'"
+                else
+                    case "${value}" in
+                        chroot|podman)
+                            osruntime[${name}]=${value}
+                            ;;
+                        *)
+                            exit_error "osruntime '${value}' for '${name}' not supported"
+                            ;;
+                    esac
+                fi
                 ;;
             numa-node)
                 # node-node is per engine:
@@ -246,7 +276,7 @@ function process_remotehost_opts() {
                 #TODO: validate correct format of <client-server-label>
                 name=`echo $val | awk -F: '{ print $1 }'`
                 value=`echo $val | awk -F: '{ print $2 }'`
-                if [ ! -z "$name}" -a ! -z "$value" ]; then
+                if [ ! -z "${name}" -a ! -z "${value}" ]; then
                     cpuPartitioning[$name]=$value
                 else
                     exit_error "Could not properly decode cpu-partitioning for '$val'"
@@ -292,8 +322,7 @@ function remotehost_req_check() {
 function launch_osruntime() {
     local this_cs_label this_cs_log_file base_cmd cs_cmd cs_rb_env env_file
     local env_opts existing_container container_id container_mount container_name fs
-    local total_cpu_partitions
-    echo "osruntime: $osruntime"
+    local total_cpu_partitions tmp_osruntime
 
     # create working directories
     do_ssh $user@$host /bin/mkdir -p $remote_cfg_dir
@@ -327,7 +356,14 @@ function launch_osruntime() {
     # For each client and server launch the actual script which will run it.
     count=1
     for this_cs_label in ${clients[@]} ${servers[@]}; do
-        container_name="${endpoint_label}_${run_id}_${this_cs_label}"
+        tmp_osruntime=${osruntime[default]}
+        set +u
+        if [ ! -z "${osruntime[$this_cs_label]}" ]; then
+            tmp_osruntime=${osruntime[$this_cs_label]}
+        fi
+        set -u
+
+        container_name="${endpoint_label}_${run_id}_${this_cs_label}_${tmp_osruntime}"
         existing_container=`do_ssh $user@$host podman ps --all --format "{{.Names}}" | grep ^$container_name$`
         if [ ! -z "$existing_container" ]; then
             echo "WARNING: found existing container '$existing_container', deleting"
@@ -361,52 +397,50 @@ function launch_osruntime() {
             this_disable_tools="$disable_tools"
         fi
 
-        if [ "$osruntime" == "chroot" ]; then
+        if [ "${tmp_osruntime}" == "chroot" ]; then
             echo "using chroot"
 
-            if [ "$osruntime" == "chroot" ]; then
-                echo "Adding mount for chroot osruntime"
-                container_id=`do_ssh $user@$host podman create --name $container_name $image`
-                echo "container_id: $container_id"
-                echo "$container_id" >>$endpoint_run_dir/chroot-container-id.txt
-                container_mount=`do_ssh $user@$host podman mount "$container_id"`
-                echo "container_mount: $container_mount"
-                echo "$container_mount" >>$endpoint_run_dir/chroot-container-mount.txt
-                echo "container_name: $container_name"
-                echo "$container_name" >>$endpoint_run_dir/chroot-container-name.txt
-                if [ ! -z "$container_mount" ]; then
-                    echo "Container mount: $container_mount"
-                    # Allow the user to more easily inspect failed runs
-                    echo "Mapping container /tmp to host $remote_data_dir"
-                    do_ssh $user@$host mkdir -p $container_mount/tmp
-                    do_ssh $user@$host mount --verbose --options bind $remote_data_dir $container_mount/tmp
-                    echo "Adding host directories to container mount"
-                    if [ "$host_mounts" != "" ]; then
-                        local oldIFS=$IFS
-                        IFS=" "
-                        for fs in $host_mounts; do
-                            chroot_rbind_mounts+=" $fs"
-                        done
-                        IFS=$oldIFS
-                    fi
-                    for fs in ${chroot_rbind_mounts}; do
-                        echo "Adding ${fs} to ${container_mount}"
-                        do_ssh $user@$host mkdir -p $container_mount/$fs
-                        do_ssh $user@$host mount --verbose --options rbind /$fs $container_mount/$fs
-                        do_ssh $user@$host mount --verbose --make-rslave $container_mount/$fs
-                        echo
+            echo "Adding mount for chroot osruntime"
+            container_id=$(do_ssh ${user}@${host} podman create --name ${container_name} ${image})
+            echo "container_id: ${container_id}"
+            echo "${this_cs_label} ${container_id}" >>${endpoint_run_dir}/chroot-container-id.txt
+            container_mount=$(do_ssh ${user}@${host} podman mount "${container_id}")
+            echo "container_mount: ${container_mount}"
+            echo "${this_cs_label} ${container_mount}" >>${endpoint_run_dir}/chroot-container-mount.txt
+            echo "container_name: $container_name"
+            echo "${this_cs_label} ${container_name}" >>${endpoint_run_dir}/chroot-container-name.txt
+            if [ ! -z "${container_mount}" ]; then
+                echo "Container mount: ${container_mount}"
+                # Allow the user to more easily inspect failed runs
+                echo "Mapping container /tmp to host ${remote_data_dir}"
+                do_ssh ${user}@${host} mkdir -p ${container_mount}/tmp
+                do_ssh ${user}@${host} mount --verbose --options bind ${remote_data_dir} ${container_mount}/tmp
+                echo "Adding host directories to container mount"
+                if [ "${host_mounts}" != "" ]; then
+                    local oldIFS=${IFS}
+                    IFS=" "
+                    for fs in ${host_mounts}; do
+                        chroot_rbind_mounts+=" ${fs}"
                     done
-                    # for chroot osruntime we can also simply copy the ssh key
-                    echo "Copying ssh key to $user@$host:$container_mount/tmp/ for chroot runtime"
-                    pushd "$config_dir" >/dev/null
-                    do_scp "" "rickshaw_id.rsa" "$user@$host" "$container_mount/tmp/"
-                    popd >/dev/null
-                    do_ssh $user@$host /bin/cp /etc/hosts $container_mount/etc/
-                    do_ssh $user@$host /bin/cp /etc/resolv.conf $container_mount/etc/
-                else
-                    echo "Container mount not found, exiting"
-                    exit 1
+                    IFS=${oldIFS}
                 fi
+                for fs in ${chroot_rbind_mounts}; do
+                    echo "Adding ${fs} to ${container_mount}"
+                    do_ssh ${user}@${host} mkdir -p ${container_mount}/${fs}
+                    do_ssh ${user}@${host} mount --verbose --options rbind /${fs} ${container_mount}/${fs}
+                    do_ssh ${user}@${host} mount --verbose --make-rslave ${container_mount}/${fs}
+                    echo
+                done
+                # for chroot osruntime we can also simply copy the ssh key
+                echo "Copying ssh key to ${user}@${host}:${container_mount}/tmp/ for chroot runtime"
+                pushd "${config_dir}" >/dev/null
+                do_scp "" "rickshaw_id.rsa" "${user}@${host}" "${container_mount}/tmp/"
+                popd >/dev/null
+                do_ssh ${user}@${host} /bin/cp /etc/hosts ${container_mount}/etc/
+                do_ssh ${user}@${host} /bin/cp /etc/resolv.conf ${container_mount}/etc/
+            else
+                echo "Container mount not found, exiting"
+                exit 1
             fi
 
             base_cmd="/usr/local/bin/bootstrap"
@@ -416,7 +450,7 @@ function launch_osruntime() {
             base_cmd+=" --cs-label=$this_cs_label"
             base_cmd+=" --base-run-dir=$base_run_dir"
             base_cmd+=" --endpoint=remotehost"
-            base_cmd+=" --osruntime=$osruntime"
+            base_cmd+=" --osruntime=${tmp_osruntime}"
             base_cmd+=" --max-sample-failures=$max_sample_failures"
             base_cmd+=" --max-rb-attempts=$max_rb_attempts"
             base_cmd+=" --cpu-partitions=${total_cpu_partitions}"
@@ -431,7 +465,7 @@ function launch_osruntime() {
             # Note that --endpoint-run value must be hard-coded to /endpoint-run becaue of chroot
             # Same will be true for running podman
             cs_cmd="nohup chroot $container_mount $base_cmd >$remote_logs_dir/$this_cs_log_file &"
-        elif [ "$osruntime" == "podman" ]; then
+        elif [ "${tmp_osruntime}" == "podman" ]; then
             echo "using podman"
 
             env_file="${this_cs_label}_env.txt"
@@ -445,7 +479,7 @@ function launch_osruntime() {
             echo "cpu_partitions=${total_cpu_partitions}"   >> ${endpoint_run_dir}/${env_file}
             echo "cpu_partition_index=${count}"             >> ${endpoint_run_dir}/${env_file}
             echo "endpoint=remotehost"                      >> ${endpoint_run_dir}/${env_file}
-            echo "osruntime=$osruntime"                     >> ${endpoint_run_dir}/${env_file}
+            echo "osruntime=${tmp_osruntime}"               >> ${endpoint_run_dir}/${env_file}
             echo "max_sample_failures=$max_sample_failures" >> ${endpoint_run_dir}/${env_file}
             echo "max_rb_attempts=$max_rb_attempts"         >> ${endpoint_run_dir}/${env_file}
             echo "ssh_id=${ssh_id}"                         >> ${endpoint_run_dir}/${env_file}
@@ -508,21 +542,30 @@ function launch_osruntime() {
 }
 
 function move_remotehost_logs() {
-    local this_cs_label remote_cs_log_file container_name
+    local this_cs_label remote_cs_log_file container_name delete_remote_dir
+    delete_remote_dir=0
     mkdir -p "$client_server_logs_dir"
     for this_cs_label in ${clients[@]} ${servers[@]}; do
-        if [ "${osruntime}" == "chroot" ]; then
+        tmp_osruntime=${osruntime[default]}
+        set +u
+        if [ ! -z "${osruntime[$this_cs_label]}" ]; then
+            tmp_osruntime=${osruntime[$this_cs_label]}
+        fi
+        set -u
+
+        if [ "${tmp_osruntime}" == "chroot" ]; then
+            delete_remote_dir=1
             remote_cs_log_file="$remote_logs_dir/$this_cs_label.txt"
             pushd / >/dev/null
             do_scp "$user@$host" "$remote_cs_log_file" "" / && \
                 mv $remote_cs_log_file $client_server_logs_dir
             popd >/dev/null
-        elif [ "${osruntime}" == "podman" ]; then
-            container_name="${endpoint_label}_${run_id}_${this_cs_label}"
+        elif [ "${tmp_osruntime}" == "podman" ]; then
+            container_name="${endpoint_label}_${run_id}_${this_cs_label}_${tmp_osruntime}"
             do_ssh $user@$host podman logs ${container_name} > "${client_server_logs_dir}/${this_cs_label}.txt"
         fi
     done
-    if [ "${osruntime}" == "chroot" ]; then
+    if [ "${delete_remote_dir}" == "1" ]; then
         do_ssh ${user}@${host} /bin/rm -r ${remote_dir}
     fi
 }
