Updates to improve function and reliability of endpoints -Ensure /usr/local/bin/ is in PATH for client-server-script -Update timeouts -Clean up of variables and "set -u" for base and remotehost -Mount /var/run for k8s pods to get access to more host info for tools -Use podman instead of buildah for remotehost to mount container image  -Some remotehosts like RHCOS will not have buildah -Allow a non-root user for the remotehost endpoint  -the user must be able to sudo to root without a password -Catch error in rickshaw-run for wrong tool name in tool config

diff --git a/endpoints/remotehost/remotehost b/endpoints/remotehost/remotehost
--- a/endpoints/remotehost/remotehost
+++ b/endpoints/remotehost/remotehost
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -u
 
 # vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
 
@@ -42,35 +43,86 @@ fi
 endpoint_name="remotehost"
 osruntime="chroot"
 userenv="rhubi8"
+user="root"
+ssh_opts="-o StrictHostKeyChecking=no -o PasswordAuthentication=no"
 
-function ssh_cmd() {
-    local user_host=$1; shift
-    ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no $user_host $@
+function do_ssh() {
+    local user_host user host ssh_cmd
+    user_host=$1; shift
+    user=`echo $user_host | awk -F@ '{print $1}'`
+    host=`echo $user_host | awk -F@ '{print $2}'`
+    ssh_cmd=""
+    if [ -z "$user" ]; then
+        exit_error "do_ssh: user was blank: $user_host"
+    fi
+    if [ -z "$host" ]; then
+        exit_error "do_ssh: host was blank: $user_host"
+    fi
+    if [ "$user" != "root" ]; then
+        ssh_cmd="ssh $ssh_opts $user_host sudo bash -c \"$@\""
+    else
+        ssh_cmd="ssh $ssh_opts $user_host $@"
+    fi
+    $ssh_cmd
+    local rc=$?
+    return $rc
 }
 
-function scp_cmd() {
-    scp -o StrictHostKeyChecking=no -o PasswordAuthentication=no "$1" "$2"
+function do_scp() {
+    # The following allows for using a non-root user>
+    # If a non-root user is used, that user must have root-priv
+    # no password prompt required.
+    local src dst dst_sudo_cmd dst_path dst_user_host dst_user dst_cmd
+    local src_sudo_cmd src_path src_user_host src_user src_sudo_cmd src_cmd
+    src=$1; shift # [<user>@<host>:]<source> source can be a dir or file
+                        # If a dir, the full dir is used when copied to the destination
+    dst=$1; shift # [<user>@<host>:]<destination> destination should be a dir, not a file
+
+    if echo $dst | grep -q -- "@"; then
+        dst_sudo_cmd=""
+        dst_path=`echo $dst | awk -F: '{print $2}'`
+        dst_user_host=`echo $dst | awk -F: '{print $1}'`
+        dst_user=`echo $dst_user_host | awk -F@ '{print $1}'`
+        if [ "$dst_user" != "root" ]; then
+            local dst_sudo_cmd="sudo"
+        fi
+        dst_cmd="ssh $ssh_opts $dst_user_host $dst_sudo_cmd tar -C $dst_path -xf -"
+    else
+        dst_cmd="tar -C $dst -xf -"
+    fi
+
+    if echo $src | grep -q -- "@"; then
+        src_sudo_cmd=""
+        src_path=`echo $src | awk -F: '{print $2}'`
+        src_user_host=`echo $src | awk -F: '{print $1}'`
+        src_user=`echo $src_user_host | awk -F@ '{print $1}'`
+        if [ "$src_user" != "root" ]; then
+            src_sudo_cmd="sudo"
+        fi
+        src_cmd="ssh $ssh_opts $src_user_host $src_sudo_cmd tar -cf - $src_path"
+    else
+        src_cmd="tar -cf - $src"
+    fi
+
+    $src_cmd | $dst_cmd
 }
 
 function cleanup_osruntime() {
-    echo "doing cleanup"
+    local container_name
+    echo "Doing cleanup"
+    container_name="${endpoint_label}_$run_id"
     if [ "$osruntime" == "chroot" ]; then
-        for fs in dev proc sys; do
-            ssh_cmd root@$host umount $container_mount/$fs
-        done
-        echo "Removing mount $container_name for chroot osruntime"
-        ssh_cmd root@$host buildah unmount "$container_name"
         echo "Removing container $container_name for chroot runtime"
-        ssh_cmd root@$host buildah rm "$container_name"
+        do_ssh $user@$host podman rm "$container_name"
     fi
 }
 
 function process_remotehost_opts() {
-    local endpoint_opts="$1"
-    local this_opt=""
+    local endpoint_opts this_opt arg val
+    endpoint_opts="$1"
     for this_opt in `echo $endpoint_opts | sed -e 's/,/ /g'`; do
-        local arg=`echo $this_opt | awk -F: '{print $1}'`
-        local val=`echo $this_opt | awk -F: '{print $2}'`
+        arg=`echo $this_opt | awk -F: '{print $1}'`
+        val=`echo $this_opt | awk -F: '{print $2}'`
         case "$arg" in
             client|server|clients|servers)
                 addto_clients_servers "$arg" "$val"
@@ -91,6 +143,9 @@ function process_remotehost_opts() {
             host)
                 host=$val
                 ;;
+            user)
+                user=$val
+                ;;
             *)
                 if echo $arg | grep -q -- "="; then
                     echo "You can't use a \"=\" for assignment in endpoint options"
@@ -100,21 +155,16 @@ function process_remotehost_opts() {
                 ;;
         esac
     done
+    if [ "$do_validate" != "1" ]; then 
+        remote_logs_dir="/var/lib/crucible/$endpoint_label-logs_$run_id"
+    fi
 }
 
 function remotehost_req_check() {
-    ssh_cmd root@$host uptime >/dev/null || exit_error "Could not ssh to $host"
-    if [ "$osruntime" == "chroot" ]; then
-        ssh_cmd root@$host buildah --version >/dev/null 2>&1 ||\
-            ssh_cmd root@$host yum install -y buildah >/dev/null 2>&1 ||\
-              exit 1
-    elif [ "$osruntime" == "podman" ]; then
-        ssh_cmd root@$host podman --version >/dev/null 2>&1 ||\
-            ssh_cmd root@$host yum install -y podman >/dev/null 2>&1 ||\
-                exit 1
-    else # Unsupported osruntime
-        exit 1
-    fi
+    do_ssh $user@$host uptime >/dev/null || exit_error "Could not ssh to $host"
+    do_ssh $user@$host podman --version >/dev/null 2>&1 ||\
+        do_ssh $user@$host yum install -y podman >/dev/null 2>&1 ||\
+        exit_error "Podman not installed and could not install it" 
     # Validation returns what clients and servers would be used and the userenv
     if [ "$do_validate" == 1 ]; then
         echo_clients_servers
@@ -124,63 +174,76 @@ function remotehost_req_check() {
 }
 
 function launch_osruntime() {
+    local this_cs_label this_cs_log_file base_cmd cd_cmd cs_rb_env
+    local env_opts existing_container container_id container_mount container_name fs
     echo osruntime: $osruntime
+    echo ensuring container image is pulled to $host
+    do_ssh $user@$host podman pull $image
+    container_name="${endpoint_label}_$run_id"
+    existing_container=`do_ssh $user@$host podman ps -a --format "{{.Names}}" | grep ^$container_name$`
+    if [ ! -z "$existing_container" ]; then
+        echo "WARNING: found existing container '$existing_container', deleting"
+        do_ssh $user@$host podman rm $container_name
+    fi
     if [ "$osruntime" == "chroot" ]; then
-        # Delete old container if there is one
-        existing_container=`ssh_cmd root@$host buildah containers --format "{{.ContainerName}}" | grep $endpoint_label`
-        if [ ! -z "$existing_container" ]; then
-            ssh_cmd root@$host buildah rm $endpoint_label
-        fi
         echo "Adding mount for chroot osruntime"
-        container_name=`ssh_cmd root@$host buildah from --name $endpoint_label $image`
-        if [ "$container_name" == "$endpoint_label" ]; then
-            container_mount=`ssh_cmd root@$host buildah mount "$container_name"`
-            echo "container mount: $container_mount"
+        container_id=`do_ssh $user@$host podman create --name $container_name $image`
+        container_mount=`do_ssh $user@$host podman mount "$container_id"`
+        if [ ! -z "$container_mount" ]; then
+            echo "Container mount: $container_mount"
+            echo "Adding /dev /proc /sys to container mount"
             for fs in dev proc sys; do
-                ssh_cmd root@$host mount --verbose --options bind /$fs $container_mount/$fs
+                do_ssh $user@$host mount --verbose --options bind /$fs $container_mount/$fs
             done
-            endpoint_run_dir=$container_mount/endpoint-run
             # for chroot osruntime we can also simply copy the ssh key
-            scp_cmd "$config_dir/rickshaw_id.rsa" "root@$host:$container_mount/tmp/rickshaw_id.rsa"
-            scp_cmd /etc/hosts "root@$host:$container_mount/etc/"
-            scp_cmd /etc/resolv.conf "root@$host:$container_mount/etc/"
+            echo "Copying ssh key to $user@$host:$container_mount/tmp/ for chroot runtime"
+            pushd "$config_dir" >/dev/null
+            do_scp "rickshaw_id.rsa" "$user@$host:$container_mount/tmp/"
+            popd >/dev/null
+            do_ssh $user@$host /bin/cp /etc/hosts $container_mount/etc/
+            do_ssh $user@$host /bin/cp /etc/resolv.conf $container_mount/etc/
+        else
+            echo "Container mount not found, exiting"
+            exit 1
         fi
-    elif [ "$osruntime" == "podman" ]; then
-        echo "Creating container for podman osruntime"
-        # Delete old container if there is one
-        #existing_container=`buildah containers --format "{{.ContainerName}}" | grep $endpoint_label`
-        #if [ ! -z "$existing_container" ]; then
-            #buildah rm $endpoint_label
-        #fi
-        # Need to add ssh key with volume mapping
     fi
 
     # For each client and server launch the actual script which will run it.
-    ssh_cmd root@$host /bin/mkdir -p $client_server_logs_dir
+    do_ssh $user@$host /bin/mkdir -p $remote_logs_dir
     for this_cs_label in ${clients[@]} ${servers[@]}; do
-        this_cs_log_file="$client_server_logs_dir/$this_cs_label.txt"
+        this_cs_log_file="$this_cs_label.txt"
         base_cmd="$client_server_run_script --rickshaw-host=$hostname"
-        base_cmd="$base_cmd --endpoint-run-dir=$endpoint_run_dir --cs-label=$this_cs_label $cs_rb_opts"
-        base_cmd="$base_cmd --base-run-dir=$base_run_dir"
+        base_cmd+=" --endpoint-run-dir=$endpoint_run_dir --cs-label=$this_cs_label $cs_rb_opts"
+        base_cmd+=" --base-run-dir=$base_run_dir"
         if [ "$osruntime" == "chroot" ]; then
             echo "using chroot"
             # Note that --endpoint-run value must be hard-coded to /endpoint-run becaue of chroot
             # Same will be true for running podman
-            cmd="chroot $container_mount $base_cmd"
-            echo -e "About to run using nohup:\n$cmd\n"
-            ssh_cmd root@$host "nohup $cmd >$this_cs_log_file &"
+            cs_cmd="nohup chroot $container_mount $base_cmd >$remote_logs_dir/$this_cs_log_file &"
+            echo -e "About to run:\n$cs_cmd\n"
+            do_ssh $user@$host "$cs_cmd"
         elif [ "$osruntime" == "podman"]; then
             echo doing podman runtime
+            cs_rb_env=`echo "$cs_rb_opts" | sed -e 's/ --/,/g'`
+            env_opts="--env rickshaw-host=localhost,endpoint-run-dir=$endpoint_run_dir"
+            env_opts+=",cs-label=$this_cs_label,base-run-dir=$base_run_dir"
+            env_opts+="$cs_rb_env"
+            podman run -t $env_opts $image
         fi
     done
     echo "This endpiont deployed"
 }
 
-function get_remotehost_logs() {
+function move_remotehost_logs() {
+    local this_cs_label remote_cs_log_file
     mkdir -p "$client_server_logs_dir"
     for this_cs_label in ${clients[@]} ${servers[@]}; do
-        this_cs_log_file="$client_server_logs_dir/$this_cs_label.txt"
-        scp_cmd "root@$host:$this_cs_log_file" "$this_cs_log_file"
+        remote_cs_log_file="$remote_logs_dir/$this_cs_label.txt"
+        pushd / >/dev/null
+        do_scp "$user@$host:$remote_cs_log_file" / && \
+        mv $remote_cs_log_file $client_server_logs_dir && \
+        do_ssh $user@$host /bin/rm -r $remote_logs_dir
+        popd >/dev/null
     done
 }
 
@@ -193,6 +256,6 @@ launch_osruntime
 process_prebench_roadblocks
 process_bench_roadblocks
 process_postbench_roadblocks
-get_remotehost_logs
+move_remotehost_logs
 cleanup_osruntime
 process_final_roadblocks
