add support for podman osruntime in remotehost endpoint
- fix many small bugs throughout the existing code

- update the logging output for easier interpretation

- rearrange code to facilitate sharing between osruntime options

- move non-shared osruntime code into osruntime specific code blocks

diff --git a/endpoints/remotehost/remotehost b/endpoints/remotehost/remotehost
--- a/endpoints/remotehost/remotehost
+++ b/endpoints/remotehost/remotehost
@@ -188,15 +188,19 @@ function do_scp() {
 }
 
 function cleanup_osruntime() {
-    local container_name
+    local container_name container_image
     echo "Doing osruntime cleanup"
+    echo
     echo "All mounts on this remote host:"
     do_ssh $user@$host mount
     echo
-    echo "All podman container mounts:"
-    do_ssh $user@$host podman mount -a
+    echo "All podman pods:"
+    do_ssh $user@$host podman ps --all
     echo
-    container_name="${endpoint_label}_$run_id"
+    echo "All podman container mounts:"
+    do_ssh $user@$host podman mount
+    echo
+    container_name="${endpoint_label}_${run_id}"
     if [ "$osruntime" == "chroot" ]; then
 
         if [ -e $endpoint_run_dir/chroot-container-mount.txt ]; then
@@ -211,25 +215,28 @@ function cleanup_osruntime() {
         else
             echo "WARNING: the file with container base mount [$endpoint_run_dir/chroot-container-mount.txt] could not be found"
         fi
-
-        echo "Removing container with name [$container_name]"
-        do_ssh $user@$host podman rm $container_name
-
-        if [ -e $endpoint_run_dir/chroot-container-image.txt ]; then
-            container_image=`cat $endpoint_run_dir/chroot-container-image.txt`
-            echo "Removing container image [$container_image]"
-            do_ssh $user@$host podman rmi $container_image
-        else
-            echo "WARNING: container image file [$endpoint_run_dir/chroot-container-image.txt] could not be found"
-        fi
-
-        echo "Remaining containers on this remote host:"
-        do_ssh $user@$host podman ps -a
-        echo "Remaining container mounts on this remote host:"
-        do_ssh $user@$host podman mount -a
-        echo "Remaining container images on this remote host:"
-        do_ssh $user@$host podman img -a
+    #elif [ "${osruntime}" == "podman" ]; then
+        # podman specific things would go here...
     fi
+
+    echo "Removing container with name [$container_name]"
+    do_ssh $user@$host podman rm $container_name
+
+    if [ -e $endpoint_run_dir/chroot-container-image.txt ]; then
+        container_image=`cat $endpoint_run_dir/chroot-container-image.txt`
+        echo "Removing container image [$container_image]"
+        do_ssh $user@$host podman rmi $container_image
+    else
+        echo "WARNING: container image file [$endpoint_run_dir/chroot-container-image.txt] could not be found"
+    fi
+
+    echo "Remaining containers on this remote host:"
+    do_ssh $user@$host podman ps --all
+    echo "Remaining container mounts on this remote host:"
+    do_ssh $user@$host podman mount
+    echo "Remaining container images on this remote host:"
+    do_ssh $user@$host podman images --all
+    echo
 }
 
 function process_remotehost_opts() {
@@ -305,6 +312,7 @@ function process_remotehost_opts() {
     done
     if [ "$do_validate" != "1" ]; then
         remote_dir="/var/lib/crucible/${endpoint_label}_${run_id}"
+        remote_cfg_dir="${remote_dir}/cfg"
         remote_logs_dir="${remote_dir}/logs"
         remote_data_dir="${remote_dir}/data/tmp"
     fi
@@ -324,22 +332,24 @@ function remotehost_req_check() {
 }
 
 function launch_osruntime() {
-    local this_cs_label this_cs_log_file base_cmd cd_cmd cs_rb_env
+    local this_cs_label this_cs_log_file base_cmd cs_cmd cs_rb_env env_file
     local env_opts existing_container container_id container_mount container_name fs
-    echo osruntime: $osruntime
+    echo "osruntime: $osruntime"
 
     # create working directories
+    do_ssh $user@$host /bin/mkdir -p $remote_cfg_dir
     do_ssh $user@$host /bin/mkdir -p $remote_logs_dir
     do_ssh $user@$host /bin/mkdir -p $remote_data_dir
 
-    echo ensuring container image is pulled to $host
+    echo "ensuring container image is pulled to $host"
     do_ssh $user@$host podman pull $image
-    container_name="${endpoint_label}_$run_id"
-    existing_container=`do_ssh $user@$host podman ps -a --format "{{.Names}}" | grep ^$container_name$`
+    container_name="${endpoint_label}_${run_id}"
+    existing_container=`do_ssh $user@$host podman ps --all --format "{{.Names}}" | grep ^$container_name$`
     if [ ! -z "$existing_container" ]; then
         echo "WARNING: found existing container '$existing_container', deleting"
         do_ssh $user@$host podman rm $container_name
     fi
+    echo "$image" >$endpoint_run_dir/chroot-container-image.txt
     if [ "$osruntime" == "chroot" ]; then
         echo "Adding mount for chroot osruntime"
         container_id=`do_ssh $user@$host podman create --name $container_name $image`
@@ -347,7 +357,6 @@ function launch_osruntime() {
         container_mount=`do_ssh $user@$host podman mount "$container_id"`
         echo "$container_id" >$endpoint_run_dir/chroot-container-id.txt
         echo "$container_mount" >$endpoint_run_dir/chroot-container-mount.txt
-        echo "$image" >$endpoint_run_dir/chroot-container-image.txt
         if [ ! -z "$container_mount" ]; then
             echo "Container mount: $container_mount"
             # Allow the user to more easily inspect failed runs
@@ -379,15 +388,6 @@ function launch_osruntime() {
     count=1
     for this_cs_label in ${clients[@]} ${servers[@]}; do
         this_cs_log_file="$this_cs_label.txt"
-        base_cmd="/usr/local/bin/bootstrap"
-        base_cmd+=" --rickshaw-host=$controller_ipaddr"
-        base_cmd+=" --endpoint-run-dir=$endpoint_run_dir"
-        base_cmd+=" $cs_rb_opts"
-        base_cmd+=" --cs-label=$this_cs_label $cs_rb_opts"
-        base_cmd+=" --base-run-dir=$base_run_dir"
-        base_cmd+=" --endpoint=remotehost"
-        base_cmd+=" --osruntime=$osruntime"
-        base_cmd+=" --max-sample-failures=$max_sample_failures"
 
         set +u
         cpu_partitioning=0
@@ -397,7 +397,6 @@ function launch_osruntime() {
             cpu_partitioning=${cpuPartitioning[default]}
         fi
         set -u
-        base_cmd+=" --cpu-partitioning=$cpu_partitioning"
 
         set +u
         numa_node=-1
@@ -407,51 +406,112 @@ function launch_osruntime() {
             numa_node=${numaNode[default]}
         fi
         set -u
-        if [ $numa_node -gt -1 ]; then
-            base_cmd="numactl -N $numa_node -m $numa_node $base_cmd"
-        fi
 
-        if [ $count -gt 1 ]; then
-            # Only the first client/server needs to run tools
-            echo "Skipping tools execution on $this_cs_label because a previous client/server is running tools on this host"
-            base_cmd+=" --disable-tools=1"
-        fi
         if [ "$osruntime" == "chroot" ]; then
             echo "using chroot"
+
+            base_cmd="/usr/local/bin/bootstrap"
+            base_cmd+=" --rickshaw-host=$controller_ipaddr"
+            base_cmd+=" --endpoint-run-dir=$endpoint_run_dir"
+            base_cmd+=" $cs_rb_opts"
+            base_cmd+=" --cs-label=$this_cs_label"
+            base_cmd+=" --base-run-dir=$base_run_dir"
+            base_cmd+=" --endpoint=remotehost"
+            base_cmd+=" --osruntime=$osruntime"
+            base_cmd+=" --max-sample-failures=$max_sample_failures"
+            base_cmd+=" --cpu-partitioning=$cpu_partitioning"
+            if [ $numa_node -gt -1 ]; then
+                base_cmd="numactl -N $numa_node -m $numa_node $base_cmd"
+            fi
+            if [ $count -gt 1 ]; then
+                # Only the first client/server needs to run tools
+                echo "Skipping tools execution on $this_cs_label because a previous client/server is running tools on this host"
+                base_cmd+=" --disable-tools=1"
+            fi
+
             # Note that --endpoint-run value must be hard-coded to /endpoint-run becaue of chroot
             # Same will be true for running podman
             cs_cmd="nohup chroot $container_mount $base_cmd >$remote_logs_dir/$this_cs_log_file &"
-            echo -e "About to run:\n$cs_cmd\n"
-            do_ssh $user@$host "$cs_cmd"
-            ssh_rc=$?
-            if [ $ssh_rc -gt 0 ]; then
-                echo "running chroot failed"
+        elif [ "$osruntime" == "podman" ]; then
+            echo "using podman"
+
+            env_file="${this_cs_label}_env.txt"
+
+            ssh_id=$(sed -z 's/\n/\\n/g' ${config_dir}/rickshaw_id.rsa)
+
+            echo "rickshaw_host=$controller_ipaddr"         >> ${endpoint_run_dir}/${env_file}
+            echo "endpoint_run_dir=$endpoint_run_dir"       >> ${endpoint_run_dir}/${env_file}
+            echo "cs_label=$this_cs_label"                  >> ${endpoint_run_dir}/${env_file}
+            echo "base_run_dir=$base_run_dir"               >> ${endpoint_run_dir}/${env_file}
+            echo "cpu_partitioning=$cpu_partitioning"       >> ${endpoint_run_dir}/${env_file}
+            echo "endpoint=remotehost"                      >> ${endpoint_run_dir}/${env_file}
+            echo "osruntime=$osruntime"                     >> ${endpoint_run_dir}/${env_file}
+            echo "max_sample_failures=$max_sample_failures" >> ${endpoint_run_dir}/${env_file}
+            echo "ssh_id=${ssh_id}"                         >> ${endpoint_run_dir}/${env_file}
+
+            for cs_rb_opt in $cs_rb_opts; do
+                arg=$(echo $cs_rb_opt | awk -F'=' '{print $1}')
+                value=$(echo $cs_rb_opt | awk -F'=' '{print $2}')
+
+                arg=$(echo ${arg} | sed -e 's/^--//' -e 's/-/_/g' )
+
+                echo "${arg}=${value}"                      >> ${endpoint_run_dir}/${env_file}
+            done
+
+            if pushd ${endpoint_run_dir} >/dev/null; then
+                echo "Copying ${endpoint_run_dir}/${env_file} to ${user}@${host}:/tmp"
+                do_scp "${env_file}" "${user}@${host}:${remote_cfg_dir}"
+
+                popd >/dev/null
+            else
+                echo "Failed to pushd to ${endpoint_run_dir} to scp env file"
                 exit 1
             fi
-        elif [ "$osruntime" == "podman" ]; then
-            echo doing podman runtime
-            cs_rb_env=`echo "$cs_rb_opts" | sed -e 's/ --/,/g'`
-            env_opts="--env rickshaw-host=localhost,endpoint-run-dir=$endpoint_run_dir"
-            env_opts+=",cs-label=$this_cs_label,base-run-dir=$base_run_dir"
-            env_opts+=",cpu-partitioning=$cpu_partitioning"
-            env_opts+="$cs_rb_env"
-            podman run -t $env_opts $image
+
+            cs_cmd="podman run"
+            cs_cmd+=" --detach=true"
+            cs_cmd+=" --name=${container_name}"
+            cs_cmd+=" --env-file ${remote_cfg_dir}/${env_file}"
+            cs_cmd+=" --privileged"
+            cs_cmd+=" --ipc=host"
+            cs_cmd+=" --pid=host"
+            cs_cmd+=" --net=host"
+            cs_cmd+=" --security-opt=label=disable"
+            cs_cmd+=" --mount=type=bind,source=${remote_data_dir},destination=/tmp"
+            cs_cmd+=" --mount=type=bind,source=/lib/modules,destination=/lib/modules"
+            cs_cmd+=" --mount=type=bind,source=/usr/src,destination=/usr/src"
+            cs_cmd+=" ${image}"
         fi
+
+        echo -e "About to run:\n${cs_cmd}\n"
+        do_ssh $user@$host "${cs_cmd}"
+        ssh_rc=$?
+        if [ ${ssh_rc} -gt 0 ]; then
+            echo "running ${osruntime} failed"
+            exit 1
+        fi
+
         let count=$count+1
     done
     echo "This endpoint deployed"
+    echo
 }
 
 function move_remotehost_logs() {
-    local this_cs_label remote_cs_log_file
+    local this_cs_label remote_cs_log_file container_name
     mkdir -p "$client_server_logs_dir"
     for this_cs_label in ${clients[@]} ${servers[@]}; do
-        remote_cs_log_file="$remote_logs_dir/$this_cs_label.txt"
-        pushd / >/dev/null
-        do_scp "$user@$host:$remote_cs_log_file" / && \
-        mv $remote_cs_log_file $client_server_logs_dir && \
-        do_ssh $user@$host /bin/rm -r $remote_dir
-        popd >/dev/null
+        if [ "${osruntime}" == "chroot" ]; then
+            remote_cs_log_file="$remote_logs_dir/$this_cs_label.txt"
+            pushd / >/dev/null
+            do_scp "$user@$host:$remote_cs_log_file" / && \
+                mv $remote_cs_log_file $client_server_logs_dir && \
+                do_ssh $user@$host /bin/rm -r $remote_dir
+            popd >/dev/null
+        elif [ "${osruntime}" == "podman" ]; then
+            container_name="${endpoint_label}_${run_id}"
+            do_ssh $user@$host podman logs ${container_name} > "${client_server_logs_dir}/${this_cs_label}.txt"
+        fi
     done
 }
 
