A misc set of updates: -better container cleanup for remotehost endpoint -suport numa node binding for remotehost -endpoint_remotehost_cleanup was being called twice -update userenvs for numactl

diff --git a/endpoints/remotehost/remotehost b/endpoints/remotehost/remotehost
--- a/endpoints/remotehost/remotehost
+++ b/endpoints/remotehost/remotehost
@@ -47,6 +47,7 @@ userenv="rhubi8"
 user="root"
 ssh_opts="-o StrictHostKeyChecking=no -o PasswordAuthentication=no"
 declare -A cpuPartitioning
+declare -A numaNode
 
 function endpoint_remotehost_test_stop() {
     echo "Running endpoint_remotehost_test_stop"
@@ -186,11 +187,50 @@ function do_scp() {
 
 function cleanup_osruntime() {
     local container_name
-    echo "Doing cleanup"
+    echo "Doing osruntime cleanup"
+    echo "All mounts on this remote host:"
+    do_ssh $user@$host mount
+    echo
+    echo "All podman container mounts:"
+    do_ssh $user@$host podman mount -a
+    echo
     container_name="${endpoint_label}_$run_id"
     if [ "$osruntime" == "chroot" ]; then
-        echo "Removing container $container_name for chroot runtime"
-        do_ssh $user@$host podman rm "$container_name"
+
+        if [ -e $endpoint_run_dir/chroot-container-mount.txt ]; then
+            container_mount=`cat $endpoint_run_dir/chroot-container-mount.txt`
+            for fs in proc dev dev/hugepages proc sys lib/modules usr/src boot; do
+                if [ -e $container_mount/$fs ]; then
+                    echo "Removing [$container_mount/$fs] for chroot using container [$container_name]"
+                    do_ssh $user@$host umount $container_mount/$fs
+                else
+                    echo "NOT removing [$container_mount/$fs] for chroot using container [$container_name] because it does not appear to be mounted"
+                    do_ssh $user@$host mount | grep $container_mount/$fs
+                fi
+            done
+            echo "Unmounting container base mount [$container_mount] for chroot using container [$container_name]"
+            do_ssh $user@$host umount $container_mount
+        else
+            echo "WARNING: the file with container base mount [$endpoint_run_dir/chroot-container-mount.txt] could not be found"
+        fi
+
+        echo "Removing container with name [$container_name]"
+        do_ssh $user@$host podman rm $container_name
+
+        if [ -e $endpoint_run_dir/chroot-container-image.txt ]; then
+            container_image=`cat $endpoint_run_dir/chroot-container-image.txt`
+            echo "Removing container image [$container_image]"
+            do_ssh $user@$host podman rmi $container_image
+        else
+            echo "WARNING: container image file [$endpoint_run_dir/chroot-container-image.txt] could not be found"
+        fi
+
+        echo "Remaining containers on this remote host:"
+        do_ssh $user@$host podman ps -a
+        echo "Remaining container mounts on this remote host:"
+        do_ssh $user@$host podman mount -a
+        echo "Remaining container images on this remote host:"
+        do_ssh $user@$host podman img -a
     fi
 }
 
@@ -214,6 +254,19 @@ function process_remotehost_opts() {
                         exit_error "osruntime $val not supported"
                         ;;
                 esac
+                ;;
+            numa-node)
+                # node-node is per engine:
+                # option format:: numa-node:<engine-name>:<value>
+                # <engine-name> can be 'default' to apply to any engine that is not explicitly specified
+                #TODO: validate correct format of <client-server-label>
+                name=`echo $val | awk -F: '{ print $1 }'`
+                value=`echo $val | awk -F: '{ print $2 }'`
+                if [ ! -z "$name}" -a ! -z "$value" ]; then
+                    numaNode[$name]=$value
+                else
+                    exit_error "Could not properly decode numa-node for '$val'"
+                fi
                 ;;
             userenv)
                 userenv=$val
@@ -292,9 +345,14 @@ function launch_osruntime() {
     if [ "$osruntime" == "chroot" ]; then
         echo "Adding mount for chroot osruntime"
         container_id=`do_ssh $user@$host podman create --name $container_name $image`
+        echo "$container_id"
         container_mount=`do_ssh $user@$host podman mount "$container_id"`
+        echo "$container_id" >$endpoint_run_dir/chroot-container-id.txt
+        echo "$container_mount" >$endpoint_run_dir/chroot-container-mount.txt
+        echo "$image" >$endpoint_run_dir/chroot-container-image.txt
         if [ ! -z "$container_mount" ]; then
             echo "Container mount: $container_mount"
+            # Allow the user to more easily inspect failed runs
             echo "Mapping container /tmp to host $remote_data_dir"
             do_ssh $user@$host mkdir -p $container_mount/tmp
             do_ssh $user@$host mount --verbose --options bind $remote_data_dir $container_mount/tmp
@@ -330,6 +388,7 @@ function launch_osruntime() {
         base_cmd+=" --endpoint=remotehost"
         base_cmd+=" --osruntime=$osruntime"
         base_cmd+=" --max-sample-failures=$max_sample_failures"
+
         set +u
         cpu_partitioning=0
         if [ ! -z "${cpuPartitioning[$this_cs_label]}" ]; then
@@ -339,6 +398,26 @@ function launch_osruntime() {
         fi
         set -u
         base_cmd+=" --cpu-partitioning=$cpu_partitioning"
+
+        set +u
+        numa_node=-1
+        if [ ! -z "${numaNode[$this_cs_label]}" ]; then
+            numa_node=${numaNode[$this_cs_label]}
+        elif [ ! -z "${numaNode[default]}" ]; then
+            numa_node=${numaNode[default]}
+        fi
+        set -u
+        if [ $numa_node -gt -1 ]; then
+            do_ssh $user@$host "numactl -H"
+            ssh_rc=$?
+            if [ $ssh_rc -gt 0 ]; then
+                echo "running numactl failed"
+                exit 1
+            else
+                base_cmd="numactl -N $numa_node -m $numa_node $base_cmd"
+            fi
+        fi
+
         if [ $count -gt 1 ]; then
             # Only the first client/server needs to run tools
             echo "Skipping tools execution on $this_cs_label because a previous client/server is running tools on this host"
@@ -394,8 +473,4 @@ init_common_dirs
 remotehost_req_check
 base_req_check
 launch_osruntime
-# process_prebench_roadblocks
-# process_bench_roadblocks remotehost
-# process_postbench_roadblocks
 process_roadblocks remotehost
-endpoint_remotehost_cleanup
