update error handling
- send messages on STDERR instead of STDOUT

- this allows these functions to be used inside functions whose STDOUT
  is captured

diff --git a/endpoints/base b/endpoints/base
--- a/endpoints/base
+++ b/endpoints/base
@@ -31,7 +31,7 @@ declare -A servers
 function abort_error() {
     local msg="$1"; shift
     local sync="$1"; shift
-    echo "[ERROR]$msg"
+    echo "[ERROR] ${msg}" 1>&2
     local msg_file=error.json
     echo '[{"recipient":{"type":"all","id":"all"},"user-object":{"error":"'$msg'"}}]' >$msg_file
     do_roadblock "$sync" "follower" "abort" "$msg_file"
@@ -39,8 +39,9 @@ function abort_error() {
 }
 
 function exit_error() {
-    local msg="$1"; shift
-    echo "[ERROR]$msg"
+    local msg
+    msg="$1"
+    echo "[ERROR] ${msg}" 1>&2
     exit 1
 }
 
