move some options to base
-id assignments can now be multiple ranges: 1-3+7-9, etc

diff --git a/endpoints/base b/endpoints/base
--- a/endpoints/base
+++ b/endpoints/base
@@ -23,12 +23,39 @@ abort=0
 userenv=""
 user=""
 max_sample_failures=""
+total_cpu_partitions=0
 export ssh_opts="-q -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
 declare -A clients
 declare -A servers
 declare -A collectors # For a remotehost that has no client or server, but runs tools
 declare -A id_to_bench
 declare -A bench_to_image
+declare -A cpuPartitioning
+declare -A osruntime
+cpuPartitioning[default]=0
+declare -A numaNode
+numaNode[default]=-1
+
+
+function range_to_list() {
+# converts 1-3+5-7+9-10 to 1 2 3 5 7 9 10
+# used for endpoint options specifying a range of IDs
+    local range=$1
+    local list=""
+    for this_range in `echo $range | sed -e 's/+/ /g'`; do
+        if echo $this_range | grep -q "-"; then
+            begin=`echo $this_range | awk -F- '{print $1}'`
+            end=`echo $this_range | awk -F- '{print $2}'`
+        else
+            begin=$this_range
+            end=$this_range
+        fi
+        for this_id in `seq $begin $end`; do
+            list+=" $this_id"
+        done
+    done
+    echo $list
+}
 
 function abort_error() {
     local msg="$1"; shift
@@ -153,6 +180,87 @@ function process_opts() {
                     fi
                 done
                 ;;
+                cpu-partitioning)
+                # cpu-partitioning is per engine:
+                # option format::  cpu-partitioning:<engine-label>:<value>
+                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
+                # <engine-label> can be an engine type (client, server) and a '-', followed by range(s) of numbers:
+                #   client-1-3+5-7+9-11   <-ranges must be separated with '+'
+                #TODO: validate correct format of <engine-label>
+                name=$(get_opt_field "${val}" "key")
+                value=$(get_opt_field "${val}" "value")
+                label=`echo $name | awk -F- '{print $1}'`
+                range=`echo $name | sed -e s/$label-//`
+                if [ ! -z "$name" -a ! -z "$value" ]; then
+                    if [ "$label" == "default" ]; then
+                        cpuPartitioning["default"]=$value
+                    else
+                        local list=`range_to_list $range`
+                        for this_id in $list; do
+                            cpuPartitioning[$label-$this_id]=$value
+                        done
+                    fi
+                else
+                    exit_error "Could not properly decode cpu-partitioning for '$val'"
+                fi
+                ;;
+            osruntime)
+                # osruntime is per engine:
+                # option format:: osruntime:<engine-label>:<value>
+                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
+                # <engine-label> can be an engine type (client, server) and a '-', followed by range(s) of numbers:
+                #   client-1-3+5-7+9-11   <-ranges must be separated with '+'
+                # for backwards compability values in the form of 'osruntime:<value>' will map to 'osruntime:default:<value>'
+                # backwards compability transformation
+                if ! echo "${val}" | grep -q -e '[a-zA-Z0-9\-]:[a-zA-Z0-9\-]'; then
+                    val="default:${val}"
+                fi
+                name=$(echo "${val}" | awk -F: '{ print $1 }')
+                value=$(echo "${val}" | awk -F: '{ print $2 }')
+                if [ -z "${name}" -o -z "${value}" ]; then
+                    echo "#Could not properly decode osruntime for '${val}'"
+                    exit_error "Could not properly decode osruntime for '${val}'"
+                fi
+                label=`echo $name | awk -F- '{print $1}'`
+                range=`echo $name | sed -e s/$label-//`
+                if [ "$value" != "chroot" -a "$value" != "podman"]; then
+                    echo "#osruntime '${value}' for '${name}' not supported"
+                    exit_error "osruntime '${value}' for '${name}' not supported"
+                fi
+
+                if [ "$name" == "default" ]; then
+                    osruntime["default"]=$value
+                else
+                    local list=`range_to_list $range`
+                    for this_id in $list; do
+                        osruntime[$label-$this_id]=$value
+                    done
+                fi
+                ;;
+            numa-node)
+                # node-node is per engine:
+                # option format:: numa-node:<engine-label>:<value>
+                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
+                # <engine-label> can be an engine type (client, server) and a '-', followed by range(s) of numbers:
+                #   client-1-3+5-7+9-11   <-ranges must be separated with '+'
+                #TODO: validate correct format of <engine-label>
+                name=$(get_opt_field "${val}" "key")
+                value=$(get_opt_field "${val}" "value")
+                label=`echo $name | awk -F- '{print $1}'`
+                range=`echo $name | sed -e s/$label-//`
+                if [ ! -z "$name" -a ! -z "$value" ]; then
+                    if [ "$label" == "default" ]; then
+                        numaNode["default"]=$value
+                    else
+                        local list=`range_to_list $range`
+                        for this_id in $list; do
+                            numaNode[$label-$this_id]=$value
+                        done
+                    fi
+                else
+                    exit_error "Could not properly decode numa-node for '$val'"
+                fi
+                ;;
             --)
                 shift;
                 break;
@@ -209,6 +317,45 @@ function addto_clients_servers() {
             fi
         fi
     done
+}
+
+function set_total_cpupart() {
+    for this_cs_label in ${clients[@]} ${servers[@]}; do
+        set +u
+        cpu_partitioning=0
+        if [ ! -z "${cpuPartitioning[$this_cs_label]}" ]; then
+            cpu_partitioning=${cpuPartitioning[$this_cs_label]}
+        elif [ ! -z "${cpuPartitioning[default]}" ]; then
+            cpu_partitioning=${cpuPartitioning[default]}
+        fi
+        set -u
+
+        if [ "${cpu_partitioning}" == "1" ]; then
+            (( total_cpu_partitions++ ))
+        fi
+    done
+}
+
+function set_osruntime_numanode_cpupart() {
+    set +u
+    if [ ! -z "${osruntime[$this_cs_label]}" ]; then
+        os_runtime=${osruntime[$this_cs_label]}
+    else
+        os_runtime=${osruntime[default]}
+    fi
+
+    if [ ! -z "${cpuPartitioning[$this_cs_label]}" ]; then
+        cpu_partitioning=${cpuPartitioning[$this_cs_label]}
+    elif [ ! -z "${cpuPartitioning[default]}" ]; then
+        cpu_partitioning=${cpuPartitioning[default]}
+    fi
+
+    if [ ! -z "${numaNode[$this_cs_label]}" ]; then
+        numa_node=${numaNode[$this_cs_label]}
+    else
+        numa_node=${numaNode[default]}
+    fi
+    set -u
 }
 
 function echo_clients_servers() {
